enum ActionTypesEnum {
  SET_TEST_VALUE = 'SET_TEST_VALUE',
  SET_RANDOM_NB = 'SET_RANDOM_NB',
  SET_CONNECTED_USER = 'SET_CONNECTED_USER',
  SET_IS_PRELOAD_STATE = 'SET_IS_PRELOAD_STATE',
}

export default ActionTypesEnum;
